{"uuid": "d1733e82-a9fe-4f12-9e90-1b38778c464d", "children": ["b8ea9acd-9b9d-4191-aeec-c44deba7d7f0"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "AttributeError: 'Session' object has no attribute 'testfailed'\n", "trace": "  File \"C:\\Users\\dmitr\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\dmitr\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\dmitr\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\dmitr\\PycharmProjects\\selenium_kurs_1\\page_object_pattern\\tests\\conftest.py\", line 16, in setup\n    before_failed = request.session.testfailed\n"}, "start": 1676650583659, "stop": 1676650585563}], "start": 1676650583659, "stop": 1676650585741}