{"uuid": "32dcd3dc-e5cb-4760-91a2-acc732cceb48", "children": ["e0fbd67d-8c5e-4d2a-a0e0-6bd9d6f75d38"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "AttributeError: 'Session' object has no attribute 'testfailed'\n", "trace": "  File \"C:\\Users\\dmitr\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\dmitr\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\dmitr\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\dmitr\\PycharmProjects\\selenium_kurs_1\\page_object_pattern\\tests\\conftest.py\", line 16, in setup\n    before_failed = request.session.testfailed\n"}, "start": 1676650585746, "stop": 1676650587720}], "start": 1676650585746, "stop": 1676650587736}